Traceback (most recent call last):
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/eRL_demo_SingleFilePPO.py", line 955, in <module>
    demo_discrete_action()
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/eRL_demo_SingleFilePPO.py", line 951, in demo_discrete_action
    train_and_evaluate(args)
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/eRL_demo_SingleFilePPO.py", line 742, in train_and_evaluate
    trajectory_list, logging_list = agent.explore_env(env, target_step, reward_scale, gamma)
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/eRL_demo_SingleFilePPO.py", line 367, in explore_env
    next_states, reward, done, _ = env.step(as_int)
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/eRL_demo_SingleFilePPO.py", line 489, in step_type
    state, reward, done, info = self.env.step(action * self.action_max)
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/simulator/simulator/envs/RMUA_Env_for_RL.py", line 165, in step
    done = self.simulator.step(self.decode_actions(actions))  # 只给其中一个传动作
  File "/home/dq/PycharmProjects/ReinforcementLearning/Projects/RMUA/RMUA 2021_V5.100/simulator/simulator/envs/kernel_game.py", line 233, in step
    self.agents[1].decode_actions(self.state, actions[1]))
IndexError: index 1 is out of bounds for axis 0 with size 1
ID     Step     MaxR |    avgR     stdR | avgS stdS |    objC     etc.
Act FileNotFound when load_model: output/2022-05-02_18-57-02
Critic FileNotFound when load_model: output/2022-05-02_18-57-02
pygame 2.0.1 (SDL 2.0.14, Python 3.6.2)
Hello from the pygame community. https://www.pygame.org/contribute.html